name: CI

on:
  pull_request:
    branches:
      - master
      - next
      - rc
  push:
    branches:
      - master
      - next
      - rc
  workflow_dispatch:

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['18']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Run CI steps
        run: |
          npm ci
          npm run ci
